### ISSUE TITLE
Issue with npm install (fsevents)

### ISSUE THREAD

**Issue by DiscordAnaxes** [teamcodebyte/turbo#12]
## Description

When running npm install, it returns an error:

```js
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

## Steps to reproduce

1. Fork the Repo
2. Run npm install

## Solution
Find the package.lock.json file and go to line 8299 and change this:

```js
"os": [
  "darwin"
],
```
to this:

```js
"os": [
  "darwin", "linux"
],
```
## Credit

Ashwin#6492

**Comment by 0t4u** [comment]
```json
"os": [
  "darwin", "linux", "win32"
],
```
should be better

**Comment by filipporomani** [comment]
Got same issue, thank you.

**Comment by kevinjosethomas** [comment]
Does this happen with yarn too?

**Comment by DiscordAnaxes** [comment]
> Does this happen with yarn too?

Most likely not. Yarn is built different :)
