### ISSUE TITLE
Development server insructions in README need to be fixed

### ISSUE THREAD

**Issue by thatjar** [teamcodebyte/turbo#22]
## Description

In the README file, the instructions to run a development server need to be updated.
> * run `npm run start` to start our frontend

**The script `start` doesn't exist at all.**

## Steps to reproduce

Running `npm run start` will display the error.

**Comment by ManagerCat** [comment]
Try `yarn dev`.

**Comment by thatjar** [comment]
Okay, but I opened the issue because the README is providing wrong instructions. So, it should be updated.

**Comment by thatjar** [comment]
Sorry, I think the bug label is confusing you. I only opened the issue because the instructions in the README were wrong, I shouldn't have used the bug report template

**Comment by AR-Student824** [comment]
why hasn't this been added yet? @trustedmercury
