### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by filipporomani** [teamcodebyte/turbo#23]

**Comment by macedonga** [comment]
probably

**Comment by BitesizedLion** [comment]
sounds about right.

**Comment by BitesizedLion** [comment]
![cat-smirk (1)](https://user-images.githubusercontent.com/42980888/131354199-7a3e5ffb-8734-4d1f-9657-3425253eee00.jpg)
have a pic of a cat

**Comment by thatjar** [comment]
(ah yes enhancement)
This is the Electron version of Turbo, and I'm 90% sure it's not gonna be updated anymore.
The Chromium version will be maintained tho

**Comment by BitesizedLion** [comment]
> The Chromium version will be maintained tho

assuming he figures out how to make edits

**Comment by macedonga** [comment]
lol

**Comment by thatjar** [comment]
yeah lol

**Comment by macedonga** [comment]
![]()

**Comment by BitesizedLion** [comment]
![7i9rsw0srta71](https://user-images.githubusercontent.com/42980888/131354926-1feb786b-ba85-44c1-9a1a-cd3ff70e0d14.jpg)

**Comment by thatjar** [comment]
what is this issue

**Comment by BitesizedLion** [comment]
> what is this issue

this issue is an issue

**Comment by filipporomani** [comment]
> what is this issue

**Comment by BitesizedLion** [comment]
opened or closed 
closed or opened

**Comment by thatjar** [comment]
hm.

**Comment by thatjar** [comment]
we still didnt get the answer but ok

**Comment by filipporomani** [comment]
I’ll just un star this for now.
